"""empty message

Revision ID: 0752d472136a
Revises: 21a465807940
Create Date: 2021-12-04 23:23:16.149588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0752d472136a'
down_revision = '21a465807940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('cname', sa.String(length=50), nullable=False),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('cname')
    )
    op.create_table('diseasetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease',
    sa.Column('disease_code', sa.String(length=50), nullable=False),
    sa.Column('pathogen', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['diseasetype.id'], ),
    sa.PrimaryKeyConstraint('disease_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('surname', sa.String(length=40), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cname', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cname'], ['country.cname'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('discover',
    sa.Column('cname', sa.String(length=50), nullable=False),
    sa.Column('disease_code', sa.String(length=50), nullable=False),
    sa.Column('first_enc_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cname'], ['country.cname'], ),
    sa.ForeignKeyConstraint(['disease_code'], ['disease.disease_code'], ),
    sa.PrimaryKeyConstraint('cname', 'disease_code')
    )
    op.create_table('doctor',
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('degree', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('publicservant',
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('record',
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('cname', sa.String(length=50), nullable=False),
    sa.Column('disease_code', sa.String(length=50), nullable=False),
    sa.Column('total_deaths', sa.Integer(), nullable=True),
    sa.Column('total_patients', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cname'], ['country.cname'], ),
    sa.ForeignKeyConstraint(['disease_code'], ['disease.disease_code'], ),
    sa.ForeignKeyConstraint(['email'], ['publicservant.email'], ),
    sa.PrimaryKeyConstraint('email', 'cname', 'disease_code')
    )
    op.create_table('specialize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['doctor.email'], ),
    sa.ForeignKeyConstraint(['id'], ['diseasetype.id'], ),
    sa.PrimaryKeyConstraint('id', 'email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialize')
    op.drop_table('record')
    op.drop_table('publicservant')
    op.drop_table('doctor')
    op.drop_table('discover')
    op.drop_table('users')
    op.drop_table('disease')
    op.drop_table('diseasetype')
    op.drop_table('country')
    # ### end Alembic commands ###
