"""empty message

Revision ID: ebcabab18b50
Revises: 02a9d951e7bd
Create Date: 2021-12-04 22:28:43.783820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebcabab18b50'
down_revision = '02a9d951e7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discover', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('discover', 'cname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('discover', 'disease_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'discover', ['disease_code'])
    op.create_unique_constraint(None, 'discover', ['cname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discover', type_='unique')
    op.drop_constraint(None, 'discover', type_='unique')
    op.alter_column('discover', 'disease_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('discover', 'cname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('discover', 'id')
    # ### end Alembic commands ###
